# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicPlayer
  pod 'MarqueeLabel/Swift'
  pod 'SnapKit'
  target 'MusicPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
